+persistence continuation, defaults for TMP and PERSISTENCE

diff --git a/sbin/leech b/sbin/leech
--- a/sbin/leech
+++ b/sbin/leech
@@ -49,26 +49,12 @@ if [ -z "$DOWNLOAD_DELAY" ]; then
     DOWNLOAD_DELAY=5
 fi
 
-if [ ! -z "$PERSISTENCE" ]; then
-    SQLITE=$(which sqlite3)
-    if [ -z $SQLITE ]; then
-        echo "ERROR: Persistence enabled, but `sqlite3` is not found"
-        echo "You probably need to install it."
-        exit 1
-    fi
+if [ -z "$TMP" ]; then
+    TMP=$DOWNLOADS_DIR
+fi
 
-    # TODO: create $PERSISTENCE directory
-
-    DB="$PERSISTENCE/leech.db"
-    if [ ! -f "$DB" ]; then
-        echo "WARNING: Downloads DB doesn't exist, creating it at $DB"
-        sqlite3 "$DB" "PRAGMA auto_vacuum=FULL"
-        sqlite3 "$DB" "CREATE TABLE log (url_md5 TEXT, timestamp INTEGER)"
-        # TODO: check sqlite3 created DB
-    fi
-    if [ ! -z $EXPIRATION ]; then
-        EXPIRATION=$(($EXPIRATION * 86400)) # days * seconds in a day
-    fi
+if [ -z "$PERSISTENCE" ]; then
+    PERSISTENCE=$DOWNLOADS_DIR
 fi
 
 # temporary file with RSS-feed
@@ -97,6 +83,9 @@ RFC822_TO_3339_STAGE1="s/(\w{3}),\s+([0-9]{2})\s+(\w{3})\s+([0-9]{4})\s+([0-9]{2
 if [ ! -d "$TMP" ]; then
     echo "WARNING: Temporary directory \"$TMP\" doesn't exist, creating it."
     mkdir -p "$TMP"
+    if [ ! $? -eq 0 ]; then
+        exit 1
+    fi
 fi
 
 # remove previous lunch if any
@@ -106,11 +95,42 @@ rm -f "$LUNCH"
 if [ ! -z "$DOWNLOADS_DIR" ] && [ ! -d "$DOWNLOADS_DIR" ]; then
     echo "WARNING: Downloads directory \"$DOWNLOADS_DIR\" doesn't exist, creating it."
     mkdir -p "$DOWNLOADS_DIR"
+    if [ ! $? -eq 0 ]; then
+        exit 1
+    fi
 fi
 
-# get current time if needed
-if [ ! -z $EXPIRATION ]; then
+# set expiration in seconds and current time
+if [ ! -z "$EXPIRATION" ]; then
+    EXPIRATION=$(($EXPIRATION * 86400)) # days * seconds in a day
     NOW=$(date +%s)
+fi
+
+# create persistence dir and db
+if [ ! -z "$PERSISTENCE" ]; then
+    SQLITE=$(which sqlite3)
+    if [ -z $SQLITE ]; then
+        echo "ERROR: `sqlite3` is not found"
+        echo "You probably need to install it."
+        exit 1
+    fi
+
+    if [ ! -d "$PERSISTENCE" ]; then
+        mkdir -p "$PERSISTENCE"
+        if [ ! $? -eq 0 ]; then
+            exit 1
+        fi
+    fi
+
+    DB="$PERSISTENCE/leech.db"
+    if [ ! -f "$DB" ]; then
+        echo "WARNING: Downloads DB \"$DB\" doesn't exist, creating it"
+        sqlite3 "$DB" "PRAGMA auto_vacuum=FULL"
+        sqlite3 "$DB" "CREATE TABLE log (url_md5 TEXT, timestamp INTEGER)"
+        if [ ! $? -eq 0 ]; then
+            exit 1
+        fi
+    fi
 fi
 
 # downloading
@@ -142,7 +162,7 @@ do
 
         *)
             echo "Failed"
-            continue;
+            continue
             ;;
     esac
 
@@ -167,6 +187,10 @@ do
         #
         echo "$DATA" | while read STR
         do
+            if [ -z "$STR" ]; then
+                continue
+            fi
+
             URL=$(echo $STR | sed $SED_OPTS "s/$SED_REGEX/\1/")
             DATETIME=$(echo $STR | sed $SED_OPTS "s/$SED_REGEX/\2/")
 
@@ -189,12 +213,10 @@ do
                 MD5=$(expr substr "$MD5" 1 32)
 
                 sqlite3 "$DB" "SELECT url_md5 FROM log WHERE url_md5='$MD5'" | grep "$MD5" 2>&1 >/dev/null
-                case $? in
-                    0) # grep matched md5 sum - it's in DB, skip it
-                        echo "Skipping $URL: already downloaded"
-                        continue
-                        ;;
-                esac
+                if [ $? -eq 0 ]; then
+                    echo "Skipping $URL: already downloaded"
+                    continue
+                fi
             fi
 
             echo -n "Downloading file: $URL... "
@@ -223,7 +245,7 @@ do
     rm -f "$LUNCH"
 
     # delete old records from DB, but only if expiration period is set
-    if [ ! -z "$DB" -a ! -z "$EXPIRATION" ]; then
+    if [ ! -z "$DB" ] && [ ! -z "$EXPIRATION" ]; then
         sqlite3 "$DB" "DELETE FROM log WHERE timestamp < $(($NOW - $EXPIRATION))"
     fi
 done <"$FOODS"
