+fixed formatting

diff --git a/sbin/leech b/sbin/leech
--- a/sbin/leech
+++ b/sbin/leech
@@ -69,7 +69,7 @@ if [ -z "$EXPIRATION" ]; then
 fi
 
 if [ $EXPIRATION -lt 0 ]; then
-	echo "WARNING: EXPIRATION can't be less than 1 day, otherwise $(basename $0) won't work properly. Fixed for you."
+    echo "WARNING: EXPIRATION can't be less than 1 day, otherwise $(basename $0) won't work properly. Fixed for you."
 fi
 
 if [ -z "$PERSISTENCE" ]; then
@@ -200,11 +200,11 @@ do
             fi
 
             # timestamp in RSS is in RFC822 format, it need to be converted to string understandable by `date`
-			TIMESTAMP=$(echo $STR | sed $SED_OPTS "s/$SED_REGEX/\2/")
+            TIMESTAMP=$(echo $STR | sed $SED_OPTS "s/$SED_REGEX/\2/")
             UNIXTIME=$($RFC822TOUNIX "$TIMESTAMP")
-			if [ ! $? -eq 0 ]; then
-				echo "WARNING: RSS timestamp ($TIMESTAMP) can't be parsed correctly, expiration feature might not work properly"
-			fi
+            if [ ! $? -eq 0 ]; then
+                echo "WARNING: RSS timestamp ($TIMESTAMP) can't be parsed correctly, expiration feature might not work properly"
+            fi
 
             # if expiration set, check RSS entry pub date
             if [ ! -z "$UNIXTIME" ] && [ $(($NOW - $UNIXTIME)) -gt $EXPIRATION ]; then
diff --git a/sbin/rfc822tounix b/sbin/rfc822tounix
--- a/sbin/rfc822tounix
+++ b/sbin/rfc822tounix
@@ -3,15 +3,15 @@
 # Author: Aleksey Tulinov <aleksey.tulinov@gmail.com>
 
 usage() {
-	echo "RFC822 timestamp to unixtime (in UTC) converter"
-	echo "Usage: $0 \"<RFC822DATETIME>\""
+    echo "RFC822 timestamp to unixtime (in UTC) converter"
+    echo "Usage: $0 \"<RFC822DATETIME>\""
 }
 
 # check arguments count
 #
 if [ $# -lt 1 ]; then
 usage
-	exit 1
+    exit 1
 fi
 
 SED_OPTS="-r -e" # enable extended regular expressions in sed
@@ -21,8 +21,8 @@ NUMBER_CLEANUP="s/0?(.*)/\1/" # remove leading 0 from number (because "08" is oc
 
 echo $1 | grep $GREP_OPTS "$RFC822" >/dev/null
 if [ ! $? -eq 0 ]; then
-	echo "ERROR: Given string doesn't appear to be RFC822 datetime"
-	exit 1
+    echo "ERROR: Given string doesn't appear to be RFC822 datetime"
+    exit 1
 fi
 
 # get initial unixtime from RFC822 timestamp
